### ISSUE TITLE
Build the app 

### ISSUE THREAD

**Issue by Xiphe** [Xiphe/budgetbudget#10]
requires:

 - [ ] build script that works at least locally
 - [ ] upload build artifact to github releases

**Comment by pressqu** [comment]
alright, thanks for pointing me in the right direction on twitter. I was experimenting and don't know my way around too much. 

Following you instructions I ran npm install and then npm start
resulted in the following error message. 
If you want me to create a new issue for this, let me know. 
Running node version v13.12.0
`[start:electron] App threw an error during load
[start:electron] /Users/jd/dev/budgetbudget/main/index.ts:1
[start:electron] export { default } from './bootstrap';
[start:electron] ^^^^^^
[start:electron]
[start:electron] SyntaxError: Unexpected token 'export'
[start:electron]     at Module._compile (internal/modules/cjs/loader.js:896:18)
[start:electron]     at Module.m._compile (/Users/jd/dev/budgetbudget/node_modules/ts-node/src/index.ts:837:23)
[start:electron]     at Module._extensions..js (internal/modules/cjs/loader.js:986:10)
[start:electron]     at Object.require.extensions.<computed> [as .ts] (/Users/jd/dev/budgetbudget/node_modules/ts-node/src/index.ts:840:12)
[start:electron]     at Module.load (internal/modules/cjs/loader.js:816:32)
[start:electron]     at Module._load (internal/modules/cjs/loader.js:728:14)
[start:electron]     at Module._load (electron/js2c/asar.js:717:26)
[start:electron]     at Function.Module._load (electron/js2c/asar.js:717:26)
[start:electron]     at Module.require (internal/modules/cjs/loader.js:853:19)
[start:electron]     at require (internal/modules/cjs/helpers.js:74:18)`

**Comment by Xiphe** [comment]
would like to move the discussion to https://github.com/Xiphe/budgetbudget/issues/19
this issue is about building the distributable MacOS App
