### ISSUE TITLE
Bug Unexpected end of JSON input

### ISSUE THREAD

**Issue by Conr0se** [Xiphe/budgetbudget#108]
Hi! 
I get the message "An Error occurred Unexpected end of JSON input". 
Can somebody help me please? I'm really happy with Budgetbudget and much of my financial planning is inside this beautiful app. 
Would be great of somebody could help!

**Comment by Xiphe** [comment]
Turned out the file got corrupted. I have no idea what caused the error and unfortunately the data is lost :(
