### ISSUE TITLE
Contribution docs

### ISSUE THREAD

**Issue by Xiphe** [Xiphe/budgetbudget#19]
For people that want to run the app from source locally or want to contribute there should be docs on how to setup the app and get it running.

**Comment by Xiphe** [comment]
@pressqu pointed out the following:

https://github.com/Xiphe/budgetbudget/issues/10#issuecomment-615300939

**Comment by Xiphe** [comment]
Currently trying to reproduce the issue.

**Comment by Xiphe** [comment]
Managed to reproduce it on node `12.13.0` after i've thrown away `node_modules` and did a fresh install.

investigating

**Comment by pressqu** [comment]
The issue persists on node 13.13

**Comment by Xiphe** [comment]
should be fixed on master now.
I accidentally introduced it in  [411e1ed](https://github.com/Xiphe/budgetbudget/commit/411e1ed4f4cbac594aec9a4e0fc8d30f3e4fc093#diff-95feb73f1b2d975126381e9ce90445c3L4) when i focussed on the tree-shaking for production build.

**Comment by pressqu** [comment]
@Xiphe  Got it running. Thanks
