### ISSUE TITLE
Support category sorting

### ISSUE THREAD

**Issue by Xiphe** [Xiphe/budgetbudget#28]
Acceptance criteria:

- categories are sortable
- ~~categories can be hidden~~ -> #33

**Comment by pressqu** [comment]
for the second point see #33

**Comment by pressqu** [comment]
should categories be managed in MoneyMoney? Or should users be able to create their own categories? 
What is you opinion on this?

**Comment by Xiphe** [comment]
The current situation is a bit suboptimal since MoneyMoney does not have a dedicated Category api. 

As a first step I would favour a solution where all category handling is done inside MoneyMoney (including sorting).

I think some kind of filter/hide is definitely required for the transaction categories you mentioned in #33 and I often use one-time categories that are never used again after a given time (For vacations for example).

I have no finite plan here. I will ask MoneyMoney to add a category API and then see what's next.

It would be interesting to see how this works in real usage. I can imagine situations. Especially when the categories are used in another context (for reports in MoneyMoney or another app) there might be conflicts that then could be solved by having a sub-system for categories.

**Comment by Xiphe** [comment]
I'm waiting on a response regarding a category API. And will not work on this until I know whats up.
Blocked by #39
