### ISSUE TITLE
Refresh MM data

### ISSUE THREAD

**Issue by Xiphe** [Xiphe/budgetbudget#38]
When working with budgets I want to have a button/menu-entry to manually refresh the data from MM. So that my latest transactions and category changes show up.

**Comment by fazzer4x** [comment]
I know this is only semi related. Currently BB is set to budget forward, basically to forecast expenses and generate savings. The challenge that arises has to do with bank accounts in MM that only display the last 90 days of transactions. Take ING for example. 

Should BB ever want to have features such as charts or budgeting averages: 
- will BB save transactions from MM and create a local working copy database? 
or
- should BB only pull all available transactions and go from there?

**Comment by Xiphe** [comment]
Thanks for making me aware of this @fazzer4x. moved this discussion to https://github.com/Xiphe/budgetbudget/issues/47
