### ISSUE TITLE
MoneyMoney category export

### ISSUE THREAD

**Issue by Xiphe** [Xiphe/budgetbudget#39]
Currently MoneyMoney does not have an API that exposes all categories and their meta-data.

Due to this, BB is extracting the categories from imported transactions.
Which has a few downsides:

 - unused categories can not be shown
 - order is not stable and changes whenever the oder of transactions change
 - meta-data such as budget, currency can not be used
 - category groups are derived from category name and therefore their ID is unknown.

I asked the MoneyMoney developer what he thinks of adding a category export API and am currently waiting for his response.

**Comment by fazzer4x** [comment]
So you got api access?

**Comment by Xiphe** [comment]
Yep. It's available in the current Beta and next stable release of MoneyMoney.

**Comment by Xiphe** [comment]
https://github.com/Xiphe/budgetbudget/blob/alpha/main/scripts/exportCategories.applescript
