### ISSUE TITLE
Migrate to uuid ID for categories and accounts

### ISSUE THREAD

**Issue by Xiphe** [Xiphe/budgetbudget#43]
The upcoming version of MoneyMoney will provide a category export (ref https://github.com/Xiphe/budgetbudget/issues/39). 
It will also use support getting transactions from accounts that don't have a accountNumber (like Offline/Cash accounts).

Both fixes are using a new uuid format for ids that is not compatible with the account numbers and category ids currently being used in `.budget` files.

Question is: Should I try to provide a migration for budget-files? Or would it be OK if we throw away our previous files and start fresh?

**Comment by Xiphe** [comment]
Have you already entered lots of budgets that would be hard to re-create? @MorrisJobke @jeifour ?

**Comment by jeifour** [comment]
Personally completely fine with breaking changes without easy migration methods during Alpha.

**Comment by zigulle** [comment]
same here. It´s alpha code.

**Comment by MorrisJobke** [comment]
same here. Better spend your time with other stuff. 👍

**Comment by Xiphe** [comment]
Awesome! Same here :)

But since we're in a close feedback loop I thought couldn't hurt to ask you :)

So the answer is: No, I wont try to migrate from numeric category ids and account numbers to uuids.
