### ISSUE TITLE
File format not supported. - Alpha 5 

### ISSUE THREAD

**Issue by fazzer4x** [Xiphe/budgetbudget#48]
Cannot open budgetbudget using the downloaded dmg or compiling it on my own. 
<img width="1045" alt="Bildschirmfoto 2020-05-01 um 10 35 41" src="https://user-images.githubusercontent.com/64558956/80793479-c0845d00-8b86-11ea-9540-94fd35dc558d.png">

**Comment by fazzer4x** [comment]
Basically what's happening is, that when you open BB for the first time, it won't find any budget and present this screen. Once you use File -> New Budget it's back in a working state.

**Comment by Xiphe** [comment]
This error is intended.

As described in https://github.com/Xiphe/budgetbudget/issues/43 i made changes to the way MM categories and accounts are being referred to. And decided to not provide a migration while being in alpha.

You're seeing this on startup BB tries to re-open the files you left open in your previous session.

The way to go here is, as you said: close the window and create a new Budget.

Once we're in Beta I will provide migrations if the file format changes.
