### ISSUE TITLE
Error on creating a new budget 

### ISSUE THREAD

**Issue by fazzer4x** [Xiphe/budgetbudget#49]
on  Alpha 7

```
[start:electron] Error occurred in handler for 'MM_EXPORT_ACCOUNTS': Error: Unexpectedly got string as icon
[start:electron]     at /Users/User/dev/bb-test/budgetbudget/main/moneymoney/handlers.ts:29:13
[start:electron]     at Array.map (<anonymous>)
[start:electron]     at base64Icons (/Users/User/dev/bb-test/budgetbudget/main/moneymoney/handlers.ts:21:15)
[start:electron]     at Object.<anonymous> (/Users/User/dev/bb-test/budgetbudget/main/moneymoney/handlers.ts:74:14)
[start:electron]     at step (/Users/User/dev/bb-test/budgetbudget/main/moneymoney/handlers.ts:44:23)
[start:electron]     at Object.next (/Users/User/dev/bb-test/budgetbudget/main/moneymoney/handlers.ts:25:53)
[start:electron]     at fulfilled (/Users/User/dev/bb-test/budgetbudget/main/moneymoney/handlers.ts:16:58)
[start:electron] npm run start:electron exited with code 0
```

**Comment by Xiphe** [comment]
Which MoneyMoney version are you using?
The current alpha only works with `>= 2.3.27` which is currently only available as a [beta release](https://moneymoney-app.com/beta/)

**Comment by fazzer4x** [comment]
MoneyMoney Version 2.3.26

Good to know. thanks !
I have the MAS version. Maybe I can switch

**Comment by Xiphe** [comment]
I heard that the MAS version can not use the beta-releases, sorry.

**Comment by Xiphe** [comment]
The latest version working with 2.3.26 is https://github.com/Xiphe/budgetbudget/releases/tag/v0.2.0-alpha.2
https://github.com/Xiphe/budgetbudget/tree/v0.2.0-alpha.2

**Comment by fazzer4x** [comment]
I went ahead and requested access to a beta version.

**Comment by Xiphe** [comment]
I'm closing here please reopen if this persists with next MoneyMoney release
