### ISSUE TITLE
Goes on erron on 1st start

### ISSUE THREAD

**Issue by RoberTo1111** [Xiphe/budgetbudget#65]
Hello,

after installation on Big Sur (11.0.1) its waiting for accounts (animated circles) and after a timeout it goes on following error:

An Error Ocurred
Command failed: osascript /Applications/BudgetBudget.app/Contents/Resources/scripts/exportAccounts.applescript

Regards RoberTo

**Comment by Xiphe** [comment]
Hey @RoberTo1111 

Thanks for the Bug-Report!

I have not yet updated to Big Sur, so it's not unlikely that there are some issues with it. I'll do the update within the next days and check if I can reproduce it.

A few follow ups questions:
 - Do you have MoneyMoney installed and unlocked?
 - Did everything Work before updating to Big Sur?
 - If you're comfortable with it, could you check `~/Library/Logs/BudgetBudget/main.log` and see if there are more details to the error?

**Comment by RoberTo1111** [comment]
Hey Xiphe

 it works now. I think it was a problem with unlocking moneymoney.

Thanks a lot 4 helping.

Regards

RoberTo

**Comment by Xiphe** [comment]
Great to hear!

Still if MM is locked BudgetBudget should just say 
"MoneyMoney Database is locked"
And present "Open MoneyMoney" and "Retry" buttons.

In dev-mode this view is not directly visible due to an overlay.

Please re-open if this issue re-occurs.
