### ISSUE TITLE
Build for Apple Silicon

### ISSUE THREAD

**Issue by Xiphe** [Xiphe/budgetbudget#68]
See: https://www.electronjs.org/blog/apple-silicon

Hopefully this will solve https://github.com/Xiphe/budgetbudget/issues/67

**Comment by Xiphe** [comment]
@netgitdom ab 1.0.0-beta.11 sollte jetzt immer eine arm version mit gebaut werden. Kannst du bitte mal prüfen ob der auto-updater schon jetzt auf die arm version updated? (Einfach BudgetBudget starten, dann sollte er die neue version laden, ggf. ne notification senden und dann bei restart der app auf der neusten version sein)
Kann sein, dass er noch die intel mac version lädt oder gar nichts – Dann müsstest du die [arm-beta.11](https://github.com/Xiphe/budgetbudget/releases/download/v1.0.0-beta.11/BudgetBudget-1.0.0-beta.11-arm64.dmg) bitte manuell installieren in der Hoffnung, dass es dann ab dann geht 😅

**Comment by netgitdom** [comment]
In meiner beta9er ARM Version hab ich gar keine Option zum updaten :D (und er meldet sich auch als Version 0.0.0 seh ich gerade :D ) 
Ich lade und installiere mal manuell die die beta 11.

Aber ich kann es bestätigen, beta9 ARM läuft absolut problemlos :-)

**Comment by Xiphe** [comment]
> er meldet sich auch als Version 0.0.0

Stimmt, das hatte ich ja hier lokal zusammengebastelt :D

> In meiner beta9er ARM Version hab ich gar keine Option zum updaten 

Es gibt dafür auch (bisher https://github.com/Xiphe/budgetbudget/issues/56) kein interface. Die app checkt einfach beim start im Hintergrund ob ne neue version da ist und installierst sie dann bei restart.

> Aber ich kann es bestätigen, beta9 ARM läuft absolut problemlos :-)

# 🎉

**Comment by netgitdom** [comment]
Ich habe jetzt manuell die von dir verlinkte ARM Beta11 geladen und installiert, alle 3 Accounts (2 Bankkonten und 1 Offlinekonto) laden problemlos und schnell.

Dazu hat sich MoneyMoney gerade auf 2.4.2 aktualisiert.

Beides läuft als ARM Variante.

**Comment by netgitdom** [comment]
AutoUpdater hat BudgetBudget gerade auf ARM von Beta11 auf Beta12 aktualisiert. Nur zur Info, das geht also.

**Comment by Xiphe** [comment]
fett! danke 👍
