### ISSUE TITLE
Calculate Balance including positive bookings?

### ISSUE THREAD

**Issue by mmoole** [Xiphe/budgetbudget#70]
da bin ich eben drüber gestolpert: in einer Kategorie habe ich letztendlich eine Balance von `169,82` angesammelt, dabei gibt es nur 3 Buchungen in dieser Kategorie in diesem Zeitraum:
```
-199,80 am 17.02.2020
+199,80 am 04.03.2020 (retoure)
- 29,98 am 19.05.2020
```
entsprechend müsste die Balance eigentlich `-29,98` sein, würde ich meinen...? Das gibt der Kategoriebericht von MoneyMoney auch aus.
Stattdessen scheint dieser Wert von den `199,80` abgezogen worden zu sein, warum auch immer.

**Comment by Xiphe** [comment]
Hey @mmoole

Das liegt an dem Overspend feature. Wenn wir diese Kategorie betrachten passiert folgendes:

 - Im Februar hast du `199,80` zu viel ausgegeben, die Kategorie ist mit `-199,80` im negativen Bereich.
- Am 1. März wird dieser Betrag automatisch als "Overspend in Feb" von deinem "to Budget" im März abgezogen und die Kategorie wieder auf `0` gesetzt.
- Am 4. März bekommst du `199,80` income auf die Kategorie, sie hat nun einen Balance von eben `+199,80`.
- Positive balances werden im Folgemonat nicht automatisch auf 0 gesetzt, darum sind Anfang Mai immer noch `+199,80` in der Kategorie
- Am 19.5. gehen `-29,98` ab, damit kommt die balance von `+169,82` zustande.

Lösung:

Du kannst mit einem "Rechtsklick auf die Balance einer Kategorie "Rollover overspending" aktivieren, dann werden auch negative Beträge einfach in den nächsten Monat mit übernommen. (Das Setting ist von Monat zu Monat aktiv. Wenn du im Februar aktivierst, ist es ab dann dauerhaft aktiv, du kannst es im März aber wieder deaktivieren, dass ist es nur für Feb-Mar aktiv und danach wieder nicht mehr)

**Comment by mmoole** [comment]
prima, das klappt nun mit 'rollover overspending'. 👍🏼 
Schlussendlich würde ich mir das als allgemeine Option in den Einstellungen wünschen, finde ich. Das wäre vielleicht auch am einfachsten, ansonsten müsste man irgendeinen Indikator erfinden, um erkennen zu können, wo man das eingestellt hat und wo nicht, sonst hätte man ja keine Chance, das direkt zu erkennen (außer man rechnet nach oder stolpert drüber).

**Comment by Xiphe** [comment]
Ja, ich werde ein icon hinzufügen das anzeigt wann rollover aktiviert ist.

In den allgemeinen settings sehe ich dieses Feature nicht, ich glaube es macht keinen sinn das allgemein für alle Kategorien immer an zu haben. 

ref https://github.com/Xiphe/budgetbudget/issues/54

ich mache hier erst mal zu, da das initiale problem behoben ist.
