### ISSUE TITLE
Whish for a 'This Month' Button in Toolbar

### ISSUE THREAD

**Issue by mmoole** [Xiphe/budgetbudget#72]
Although the app starts displaying the current month, after scrolling left and right in order to analyze/compare your spendings with other times, one needs to scroll quite attentively to get back to the current month.
This would be much quicker and easier if there was a 'This Month' or 'Today' button in the top bar next to the months displayed. 
Since this is widely used in calendar software, people should already be familiar with it.

**Comment by Xiphe** [comment]
fully agree. Will add this in the future

**Comment by leo-benz** [comment]
I started working on this issue since it seemes to be quite easy and beginner friendly. I will provide a PR soon.
