### ISSUE TITLE
Scrolling between categories and values out of sync

### ISSUE THREAD

**Issue by leo-benz** [Xiphe/budgetbudget#74]
When scrolling to the bottom on the right side the rows of the categories and the values can get out of sync. When scrolling back up the error recovers and the alignment is correct again.

**Occurence** Always

**Error Path**
- Open budget view
- Scroll the right hand side completely to the bottom

**Observed Behaviour**
- Alignment of categories and values out of sync
<img width="876" alt="Issue" src="https://user-images.githubusercontent.com/3419838/106603616-d16f5e00-655e-11eb-9704-23fd79671f57.png">

**Expected Behaviour**
- No scroll bar available and no scrolling possible if vertical screen space is sufficient to display all categories at once.

**Remarks**
- When vertically resizing the window sometimes the scrolling offset can be larger then the always reproducible one row offset. In those cases also the left hand side scrolls partly out of frame.

**Comment by Xiphe** [comment]
Thanks for the report. I'll investigate this asap

**Comment by netgitdom** [comment]
I can confirm and reproduce this issue.

**Comment by Xiphe** [comment]
I can confirm this. But only when scrollbars are always visible (ref https://github.com/Xiphe/budgetbudget/issues/76#issuecomment-773942467)

Can one of you reproduce the bug when they are in "when scrolling" setting?

**Comment by leo-benz** [comment]
I can confirm that this is not reproducible if I select the "when scrolling" option. This is the case for all 3 bugs I reported. Might be 3 symptoms of the same root cause.
