### ISSUE TITLE
Scrollbar and border not in dark mode

### ISSUE THREAD

**Issue by leo-benz** [Xiphe/budgetbudget#75]
The scrollbars and the bottom window edge do not adhere to the dark mode style

**Occurrence** Always
**Severity** Low

**Steps to reproduce**
- Open Budget in dark mode
 
**Observed behaviour**
<img width="911" alt="Screenshot 2021-02-02 at 22 57 00" src="https://user-images.githubusercontent.com/3419838/106668528-a7dc2400-65aa-11eb-93fe-4723e0e52519.png">

**Expected behaviour**
- Complete application window is shown with dark style

**Comment by Xiphe** [comment]
Can confirm.

Similar to #76, this only occurs when scrollbars are set to be always visible (ref https://github.com/Xiphe/budgetbudget/issues/76#issuecomment-773942467)
