### ISSUE TITLE
Incorrect width of month view

### ISSUE THREAD

**Issue by leo-benz** [Xiphe/budgetbudget#76]
Always the right most month view in the budget overview is slightly too wide or incorrectly positioned. This causes the right side to be cut off exactly ad the decimal place of the numbers.

**Occurrence** Always
**Severity** Low

**Steps to reproduce**
- Open budget view

**Observed behaviour**
- Right most month view is cut off
- When resizing the window to only show one month the decimal number of the balance is not visible
<img width="962" alt="Screenshot 2021-02-02 at 23 04 03" src="https://user-images.githubusercontent.com/3419838/106669518-1968a200-65ac-11eb-9c90-22d5aa7b91a9.png">

**Workaround**
- Resize the window to show multiple months and scroll the months so that the relevant month is not the right most one

**Additional Remarks**
- It looks like the width that is cut off corresponds to the additional space to the right of the scrollbar which looks like it does not belong there.

**Comment by Xiphe** [comment]
Can confirm!

This bug appears when the MacOS "Show Scroll Bar" Setting is set to "Always"


<img width="678" alt="Screenshot 2021-02-05 at 11 21 19" src="https://user-images.githubusercontent.com/911218/107021463-6f079f00-67a4-11eb-96f9-d9845d88c87a.png">

**Comment by leo-benz** [comment]
For me the issue also appears when set to automatically. I am using an iMac with only a mouse and no trackpad connected. I can confirm that the issue does not appear when the setting is set to "When scrolling".

**Comment by Xiphe** [comment]
Ok 👍 Thank you for checking. I assume that "automatically" uses the "Always" setting when a Mouse is connected.

**Comment by Xiphe** [comment]
somehow the fixes cause my integration tests to fail. I'll investigate later and hopefully release today or tomorrow

**Comment by leo-benz** [comment]
I noticed that with the fixes the background of the welcome screen and sidebar of the budget screen is white instead of translucent.

**Comment by Xiphe** [comment]
@leo-benz I assume this is a development only issue, Have not figured out when this happens, let's see.

**Comment by Xiphe** [comment]
released: https://github.com/Xiphe/budgetbudget/releases/tag/v1.0.0-beta.14
