### ISSUE TITLE
Add option to exclude reserved transactions

### ISSUE THREAD

**Issue by leo-benz** [Xiphe/budgetbudget#78]
**Feature Request**
As a user I would like to have a setting to ignore reserved transactions (vorgemerkte Umsätze).

**Use-Case**
I have a monthly mortgage payment that is deducted via SEPA Lastschrift and is shown as reserved for a few days before the transaction. I always split this payment in money money into interest and repayment of the loan and assign the splits to different categories. The split in money money is only possible after the transactions has cleared. Therefore it is uncategorised while it is a reserved transaction. In the days while it has not cleared BudgetBudget shows the month as over budgeted due to the uncategorised transaction even tough I have budgeted for the interest and repayment in the respective categories. Therefore I would like BudgetBudget to ignore the reserved transaction.

Since there are probably different opinions on this I would propose to add a user setting so that this behaviour is customisable.

**Comment by Xiphe** [comment]
I understand the problem and agree that this would be a nice setting to have.

If we get the information from MM, I'll happily implement this

**Comment by leo-benz** [comment]
I just checked and the exported plist contains the boolean key
`
<key>booked</key>
<false/>
`
So the required data should be available.

**Comment by leo-benz** [comment]
I started implementing this myself and will provide a PR soon.

**Comment by Xiphe** [comment]
awesome!
