### ISSUE TITLE
Add a template fund distribution

### ISSUE THREAD

**Issue by sbonfert** [Xiphe/budgetbudget#87]
I have many categories, that should receive the same funding each month, e.g., rent, subscriptions, insurance.
It would be great to have some kind of template, that could be applied to a certain month, when I start to budget for this month.
This would allow to quickly and reliably fill out the "boring" (since always the same) part of the budget.

**Comment by Xiphe** [comment]
I agree! Closing as duplicate of https://github.com/Xiphe/budgetbudget/issues/86
