### ISSUE TITLE
Make it possible to add depots to budgeted accounts

### ISSUE THREAD

**Issue by netgitdom** [Xiphe/budgetbudget#89]
Hi,

I recently began to add some stock depots into my MoneyMoney. I see these Accounts in BudgetBudget but I can't select them.
In MoneyMoney this account is from category "Wertpapierdepots". Is it possible to somehow get these into BudgetBudget or is there any other solution to add them to my Budget ?

Regards

**Comment by Xiphe** [comment]
Hey @netgitdom 

As far as I understand, Depots don't work with Transactions (as the other accounts in MM do) but with Assets.
Assets don't share the same category pool as Transactions

<img width="412" alt="image" src="https://user-images.githubusercontent.com/911218/153402628-4aeb0fd1-d133-4ff0-8570-e0021d277c6b.png">

So I have not come up with a concept on how to integrate Assets in the current Budgeting that's based on Categories and Transactions.

Do you know of a budgeting tool that does this? Or how would you expect this to work (for example if you'd manage your budget on paper).

I personally treat my depots as external/off-budget meaning from a budget point of view i *spend* some money each month that goes to the depot (Same to the money I spend on food etc...)

And when I'd decide to trade some assets back to euros, I'd then treat that money as income once the transaction lands  on one of my other accounts and have it available for budgeting.

Let me know if this helps ✌️

**Comment by netgitdom** [comment]
Hi,

indeed it does. I didn't think about it that way. I thought, maybe it just had to be included in some kind of API call. I'll try it the way you proposed.
If it's not working for me, I'll come back with some specific idea or concept :-)

Regards

**Comment by Xiphe** [comment]
Cool! I'm closing this but you're welcome to re-open for further discussion or ideas 👍
